name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 10 8 * * 6

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Build the Docker image:latest"
      run: "docker build . --file Dockerfile --tag ${{ secrets.CR_REPO }}:$(cat Dockerfile | grep FROM | awk -F: '{print $(NF)}')"
    - name: "Build the Docker image:edge"
      run: "docker build . --file Dockerfile-edge --tag ${{ secrets.CR_REPO }}:$(cat Dockerfile-edge | grep FROM | awk -F: '{print $(NF)}')"
    - name: Login to ghcr.io
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
    - name: "Push image:latest to ghcr.io"
      run: "docker push ${{ secrets.CR_REPO }}:$(cat Dockerfile | grep FROM | awk -F: '{print $(NF)}' | awk -F- '{print $1}')"
    - name: "Push image:edge to ghcr.io"
      run: "docker push ${{ secrets.CR_REPO }}:$(cat Dockerfile-edge | grep FROM | awk -F: '{print $(NF)}')"

